services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: "8080"
      KC_PROXY: edge
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db

  bionicpro-auth:
    build:
      context: ./bionicpro-auth
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_PUBLIC_URL: http://localhost:8080
      KEYCLOAK_REALM: reports-realm
      KEYCLOAK_CLIENT_ID: bionicpro-auth
      KEYCLOAK_CLIENT_SECRET: bionicpro-auth-secret
      REDIRECT_URI: http://localhost:8001/auth/callback
      FRONTEND_URL: http://localhost:3000
      COOKIE_SECURE: "false"
      COOKIE_SAMESITE: lax
      SESSION_TTL_SECONDS: "1800"
      TOKEN_ENCRYPTION_KEY: "iw3lx6S7H4IMZsm_xrqEJqa5kHozlwoP9J0WFWHHRoU="
    depends_on:
      - keycloak

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_AUTH_URL: http://localhost:8001
    depends_on:
      - bionicpro-auth
